### ISSUE TITLE
有新增的補給站，卻無法選擇?

### ISSUE THREAD

**Issue by Speedman29** [5upergeo/PMGO-tasks-map#11]
因為40等之後，開放的補給站有變多，可能將新的補給站再新增上去???

且go fest活動課題也結束了，有空把課題改成平日使用的課題？

**Comment by HuskyHsu** [comment]
任務換回來了～
我再找時間來更新補給站資料

**Comment by Speedman29** [comment]
足感謝。百忙之中麻煩你

**Comment by Speedman29** [comment]
如果在更新補給站資料同時，能否也將課題稍為做修正?
錯誤1:晃晃斑8號，目前沒圖示。
錯誤2:土狼犬課題是抓5隻飛超惡。

**Comment by HuskyHsu** [comment]
囧～忙到今天才看到訊息
處理好囉～～～感謝回報！！

（轉牌還沒更新）

**Comment by Speedman29** [comment]
辛苦啦。也希望大大能增加彩糖任務跟吉利蛋任務，這幾個說真的回報率很高，滿熱門的。

**Comment by HuskyHsu** [comment]
哪一個彩糖任務＠＠？

**Comment by Speedman29** [comment]
像是曲3G，還連續3G之類的，只是任務只能20組XD

**Comment by Speedman29** [comment]
刷10補給站 銀鳳梨 最多人刷？

**Comment by HuskyHsu** [comment]
現在好像都只有留怪的任務耶~
某一檔活動之後怪的任務種類暴增，就把道具類的都移除了

**Comment by Speedman29** [comment]
原來是這樣啊，好的，那其他我們再自己搞定。

**Comment by HuskyHsu** [comment]
或是你覺得那些任務不重要我可以刪XDD

**Comment by Speedman29** [comment]
以目前的項目，似乎都用的到。哪個要刪也不知道好或不好。已經很濃縮了。

**Comment by Speedman29** [comment]
而且說實在的，也很懶得過要猜是哪種課題獎勵(像是投3G、投5nice、贏3等團戰以上等等)那些都要猜，個人懶得猜，直接略過，別人我是不知道，或許對其他人有幫助?

**Comment by HuskyHsu** [comment]
哈～對啊～現在的麻煩也是很多是多重獎賞，等我有空一些再來把後面資料框架的改版就可以收錄更多了

**Comment by Speedman29** [comment]
好的，感謝。就慢慢修正吧。現在課題越來越多元XD
