### ISSUE TITLE
9月平日課題有換新的，可否換成較新的課題?

### ISSUE THREAD

**Issue by Speedman29** [5upergeo/PMGO-tasks-map#13]
https://thesilphroad.com/research-tasks

參考來源網址
https://www.ptt.cc/bbs/PokemonGO/M.1567378863.A.D1A.html
捕捉時使用莓果 x5       = 雪童子*
捕捉時使用蔓莓果 x5     = 小山豬*
捕捉時使用凰梨果 x10    = 飛天螳螂*

捕捉不同種超能寶可夢 x3 = 催眠貘*
捕捉妖精寶可夢 x5       = 瑪力露
捕捉水、火、電寶可夢 x3 = 嘟嘟
捕捉一般寶可夢 x5       = 橫紋熊*
捕捉惡系寶可夢 x3       = 土狼犬*
捕捉草系、冰系寶可夢 x4 = 小海獅*
捕捉寶可夢 x15          = 穿山鼠*

傳送寶可夢 x3   = 勾魂眼*
交換寶可夢 x1   = 銅鏡怪*
遛寵得糖 x3     = 小火馬*
跟伊布拍照 x5   = 溶食獸
送禮 x10        = 狃拉*

參加團體戰 x1       = 跳跳豬*
與其它訓練師對戰 x2 = 落雷獸*
與隊長隊戰 x2       = 天然鳥*

進化寶可夢 x1 = 伊布* / 卡拉卡拉*

晃晃斑換成3號

**Comment by Speedman29** [comment]
回報一個課題項目，雪童子課題 可否改成捕捉時使用樹果 ×5？

希望盡可能跟課題名稱項目相同？

**Comment by HuskyHsu** [comment]
ＯＫ～感謝已修正

**Comment by Speedman29** [comment]
感謝 之後再麻煩加入重點課題？像是幼基拉斯、吉利蛋等等的課題。

**Comment by HuskyHsu** [comment]
會的，昨天在忙就先全部換新的上
有些也還沒確認還有沒有，等等補上

**Comment by Speedman29** [comment]
好的 ，感謝。

**Comment by Speedman29** [comment]
不好意思 可否有空把

與其它訓練師對戰 x2 = 落雷獸*修正成
與其它訓練師對戰 = 落雷獸*
(因為只需要1次)
稍微做修正，要講都一直忘記，謝謝。

捕捉不同種超能寶可夢 x3 = 催眠貘*
捕捉惡系寶可夢 x3 = 土狼犬*
較少人刷

還有希望能換成
捉龍系的迷你龍課題
團體戰獲勝5次的化石翼龍課題
感謝。

**Comment by HuskyHsu** [comment]
修改囉~感謝

**Comment by Speedman29** [comment]
可否加入世界旅遊日的活動課題

和1名訓練家成為朋友 = 朝北鼻
交換1隻來自1萬公里以外的寶可夢 = 飯匙蛇
傳送25個友誼禮物 = 拉普拉斯

活動時間 9/27-10/2凌晨4點止

**Comment by Speedman29** [comment]
看到了 有新增 謝謝
