### ISSUE TITLE
可否加入萬聖節活動課題？

### ISSUE THREAD

**Issue by Speedman29** [5upergeo/PMGO-tasks-map#15]
萬聖節活動課題

拍5隻幽靈系
 獎勵 勾魂眼

抓5隻鬼斯或怨影娃娃
獎勵 狃拉

擊敗Go火箭隊
獎勵 哭哭面具

連續3次EXCELLENT
獎勵 泥偶小人

**Comment by HuskyHsu** [comment]
補充囉～大大是在恆春那區的嗎？
我有跟報寶貝作者問了能不能掃描，不過他這幾天再忙，過陣子應該可以增加區域

**Comment by Speedman29** [comment]
主要都跑鎮內、監理站壁畫以東、出火以西、九樂寺以南、文教會館以北。

**Comment by Speedman29** [comment]
主要都跑鎮內、監理站壁畫以西、出火以東、九樂寺以南、文教會館以北。

**Comment by HuskyHsu** [comment]
ＯＫ～如果羅大有加了區域之後我再通知您

**Comment by Speedman29** [comment]
謝謝大大幫忙。

**Comment by Speedman29** [comment]
目前有新增萬聖節的課題 但沒有圖案顯示出在地圖上
