### ISSUE TITLE
可否更換成新的平日課題，課題獎勵也有些更動

### ISSUE THREAD

**Issue by Speedman29** [5upergeo/PMGO-tasks-map#17]
萬聖節課題已經下架。

連續曲球5G 改為 晃晃斑#1號的課題

捕捉時使用蕉香果X10 改為飛天螳螂

並且，把使用率較低的
抓一般屬性X5 蛇紋熊課題 可否換成 捉龍系?迷你龍課題?

**Comment by Speedman29** [comment]
有空的時候 可否將晃晃斑的圖修好。地圖上無圖案顯示

**Comment by Speedman29** [comment]
謝謝大大幫忙，目前報寶貝的恆春市區有顯示課題了。終於可以不用繞鎮內了(劃錯重點。

**Comment by HuskyHsu** [comment]
哈哈哈～週末沒開電腦沒收到訊息ＸＤ～
祝你收穫滿滿😀

**Comment by Speedman29** [comment]
謝謝，只有連續2天 顯示 今天霸工了XD

**Comment by HuskyHsu** [comment]
咦，我跟羅大問問ＸＤ

**Comment by Speedman29** [comment]
哈哈 感謝您

**Comment by HuskyHsu** [comment]
剛剛把晃晃班一號圖示補上了

**Comment by Speedman29** [comment]
感謝幫忙，報寶貝目前算是正常顯示了（我是指恆春市區內），到車城或墾丁還是會繼續回報給oh?。
