### ISSUE TITLE
可否加入新的活動課題？感謝

### ISSUE THREAD

**Issue by Speedman29** [5upergeo/PMGO-tasks-map#18]
可否新增新的活動課題，感謝

結交3位新好友
獎勵（尼多后or尼多王

訓練家對戰中獲勝1次
獎勵（三地鼠or嘟嘟利

交換一隻寶可夢
獎勵（尼多力諾or尼多娜

抓一隻尼多蘭
獎勵（尼多朗（有色違機率

抓一隻尼多朗
獎勵（尼多蘭（有色違機率

**Comment by Speedman29** [comment]
> 可否新增新的活動課題，感謝
> 
> 結交3位好友
> 獎勵（尼多后or尼多王
> 
> 訓練家對戰中獲勝1次
> 獎勵（三地鼠or嘟嘟利
> 
> 交換一隻寶可夢
> 獎勵（尼多力諾or尼多娜
> 
> 抓一尼多蘭
> 獎勵（尼多蘭（有色違機率
> 
> 抓一尼多朗
> 獎勵（尼多朗（有色違機率

**Comment by HuskyHsu** [comment]
OK~

**Comment by Speedman29** [comment]
這活動課題已經結束，可以修正為平日課題了。感謝。

**Comment by HuskyHsu** [comment]
給我一下mail或lineID，我直接開後台給你說不定會比較方便ＸＤ

**Comment by Speedman29** [comment]
哈哈，這樣好嗎（雖然看起來好像就半島在用而已XD
dancer19820416@yahoo.com.tw
