### ISSUE TITLE
錯誤資訊能否有特別的標示？

### ISSUE THREAD

**Issue by Rplus** [5upergeo/PMGO-tasks-map#2]
目前不點開任務看不出是否為誤報點
例：
![image](https://user-images.githubusercontent.com/1808835/41810360-b4806016-772f-11e8-8777-8c1dab00246c.png)

之前我是硬抓 DOM node 出來調 class，再用 CSS 控制樣式
只是不曉得這方法好不好
https://github.com/Rplus/PMGO-tasks-map/blob/66c80f4/js/main.js#L138

**Comment by HuskyHsu** [comment]
![image](https://user-images.githubusercontent.com/18141436/41889256-26ec57c8-793c-11e8-89f4-3600285e3207.png)
後來用div包起來，然後偽元素來顯示問號，不過也不知道會不會產生太多結構拖慢效能...囧

https://github.com/5upergeo/PMGO-tasks-map/commit/4865426f898ceb9d3c3eda9089774099eaa585af#diff-77ab163850ef0fa98d6a9ee9fb6bbcafL174

**Comment by Rplus** [comment]
喔喔～ 還有 `divIcon` 這 function 吶～
不過我覺得判斷 T / F 的比例會比較好一些
單獨看 F 的話，有可能會有誤報

**Comment by HuskyHsu** [comment]
好喔~我再改一下條件

**Comment by Rplus** [comment]
「再」

**Comment by HuskyHsu** [comment]
改成錯誤次數多於正確次數1次即可，先觀察幾日，有需要的話再提高門檻
