### ISSUE TITLE
 怎麼做？

### ISSUE THREAD

**Issue by bsantosh909** [5upergeo/PMGO-tasks-map#4]
你好。
我也是一個口袋妖怪的玩家，我對你的項目非常著迷。

我不是來自台灣，目前我使用谷歌翻譯來寫這篇文章，所以可能會讓人感到困惑..

但我想問你如何獲得有關台灣所有任務的信息？
我看到你通過script.google.com運行了一個腳本，但我想知道整個過程是如何完成的。

如果你很好地分享你是如何做到的，那真是太好了。

**Comment by HuskyHsu** [comment]
We collect PokéStop name and task name from the LINE bot app and the web page with rely on the strength of the masses.

![image](https://user-images.githubusercontent.com/18141436/44387398-fec71d80-a557-11e8-95db-8ef8fbe885a0.png)
![image](https://user-images.githubusercontent.com/18141436/44387366-ed7e1100-a557-11e8-8bbf-3204345a7d75.png)

**Comment by bsantosh909** [comment]
Thanks for the information.
So it seems like this project is also supported by crowdsourcing :+1:
